import monstera from "../assets/monstera.jpg";

export const plantList = [
  {
    name: "Monstera",
    price: 10,
    category: "Classique",
    id: "1ed",
    isBestSale: true,
    light: 2,
    water: 3,
    cover: monstera,
  },
  {
    name: "Ficus lyrata",
    price: 12,
    category: "Classique",
    id: "2ab",
    isBestSale: false,
    light: 2,
    water: 3,
    cover: monstera,
  },
  {
    name: "Pothos argenté",
    price: 7,
    category: "Classique",
    id: "3sd",
    isBestSale: true,
    light: 2,
    water: 3,
    cover: monstera,
  },
  {
    name: "Yucca",
    price: 6,
    category: "Classique",
    id: "4kk",
    isBestSale: true,
    light: 2,
    water: 3,
    cover: monstera,
  },
  {
    name: "Olivier",
    price: 9,
    category: "Extérieur",
    id: "5pl",
    isBestSale: false,
    light: 2,
    water: 3,
    cover: monstera,
  },
  {
    name: "Géranium",
    price: 14,
    category: "Extérieur",
    id: "6uo",
    isBestSale: false,
    light: 2,
    water: 3,
    cover: monstera,
  },
  {
    name: "Basilique",
    price: 4,
    category: "Extérieur",
    id: "7ie",
    isBestSale: false,
    light: 2,
    water: 3,
    cover: monstera,
  },
  {
    name: "Aloe",
    price: 18,
    category: "Plante grasse",
    id: "8fp",
    isBestSale: false,
    light: 2,
    water: 3,
    cover: monstera,
  },
  {
    name: "Succulente",
    price: 10,
    category: "Plante grasse",
    id: "9vn",
    isBestSale: true,
    light: 2,
    water: 3,
    cover: monstera,
  },
];
